# Generated by Django 5.0 on 2024-01-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='views',
            new_name='views_count',
        ),
    ]
