# Generated by Django 5.0 on 2024-01-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_rename_views_blog_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликовать'),
        ),
    ]
