# Generated by Django 5.0 on 2024-01-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='превью'),
        ),
    ]
