# Generated by Django 5.0 on 2024-01-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='продукт')),
                ('version_number', models.IntegerField(verbose_name='номер версии')),
                ('version_name', models.CharField(max_length=100, verbose_name='название версии')),
                ('is_active', models.BooleanField(default=True, verbose_name='признак текущей версии')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-create_date',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
