# Generated by Django 5.0 on 2024-01-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-create_date',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='наименование')),
                ('version_number', models.IntegerField(blank=True, null=True, verbose_name='номер версии')),
                ('version_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='название версии')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='признак текущей версии')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
